import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {

  const handleRedirect = () => {
    console.log("Redirect")
    window.open(
      "https://www.facebook.com/sharer.php?u=https://nextjs.org/docs/api-reference/create-next-app"
    );
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       Next app
       <button onClick={handleRedirect}>FB</button>
      </main>

      
    </div>
  )
}
